# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
cache: packages

r_github_packages:
  - mrcieu/TwoSampleMR@ieugwasr
  - WSpiller/RadialMR
  - explodecomputer/simulateGP

warnings_are_errors: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'